### ISSUE TITLE
Server side exception 

### ISSUE THREAD

**Issue by ManishMadan2882** [vukrosic/whatsapp-clone-next14#1]
![image](https://github.com/vukrosic/whatsapp-clone-next14/assets/96079232/9b63f821-7683-46d3-a60c-87761585d54a)

**Comment by vukrosic** [comment]
Currently I decided not to run the application live on Vercel, it was just live during recording. Did you want to check the website yourself?

**Comment by ManishMadan2882** [comment]
Cool, I was just checking the tutorials. I will run it on my Local .
